[package]
name = "MyToken"
version = "0.0.1"

[addresses]
MyToken = "0xFACE"

[dependencies]
MoveStdlib = { git = "https://github.com/move-language/move", subdir = "language/move-stdlib", rev = "main" }
